obstacle_range: 3.0
raytrace_range: 3.5

footprint: [[-0.205, -0.155], [-0.205, 0.155], [0.077, 0.155], [0.077, -0.155]]
#robot_radius: 0.17

inflation_radius: 3.0
cost_scaling_factor: 15.0

map_type: costmap
observation_sources: scan
scan: {sensor_frame: /om_with_tb3/base_scan, data_type: LaserScan, topic: /om_with_tb3/scan_filtered, marking: true, clearing: true}
